README.md

9/10
Windows
The python venv missing on setup but I installed and continue the setup just fine.
I cannot use Login function when I started the app from WSL ubuntu on Windows 11.
The nada test cases all working fine.
https://github.com/dekkeng/secret_addition
0xbf20064C795362e7A87F6d21fe3C57Bd99e4a9A5

Add Community example by dekkeng

---

README.md

9.5/10
Linux
Not really was just stuck because of my mistake and  not restarting the cli to get the latest $Patch Environment variable.
Yeah I was able to use the template flawlessly again there was no problem from your end but my end of not having python venv
installed and similar little hiccups . All test cases passed.It was an interesting experience looking forward to build on nillion.
https://github.com/ArslanHaaider/bllind-assistant
ETH …

Add community example by ArslanHaaider

---

README.md

10/10
Mac
https://github.com/HadesGuard/secret-addition-app
0x8656aA8186Be3ab8e268ba5B66B0Abd95870F71E

Add Community example by HadesGuard

---

README.md

_**How would you rate the usage of the npx create-nillion-app process**_
_Give a rating / 10_
10/10
_**What platform you run your CLI on**_
_Mac / Windows / Linux_
Linux
_**Did you get stuck during the CLI process?**_
_Did you experience any issues while using the latest CLI and were you able to use the template?_
_**What is your Github repository link**_
_Include the repository you worked on._
https://github.com/IkutoJP/secret_addition
_**ETH Address (Optional)**_
_Add your ETH address or ENS name_
ikutos.eth

Add Community example by IkutoJP

---

README.md

10/10
Linux
Severally got `Status:Error` uploading the program in frontend
https://github.com/0xmoei/secret_addition
0xmoei.eth

Add Community example by 0xmoei

---

README.md

_How would you rate the usage of the `npx create-nillion-app` process
Give a rating / 10_
10/10
**What platform you run your CLI on**
_Mac / Windows / Linux_
Linux
**Did you get stuck during the CLI process?**
_Did you experience any issues while using the latest CLI and were you able to use the template?_
No Issues on setup, used template. Running/building with cli took less time than updating my dev-tools)
**What is your Github repository link**
_Include the repository you worked on._
[https://github.com/grigor-aramyan/hacktoberfest-blind](https://github.com/grigor-aramyan/hacktoberfest-blind)
**ETH Address (Optional)**
_Add your ETH address or ENS name_
0xd1E2977b3af5832D59472Fd5B1493644A48035C5

community example by grigor

---

README.md

9/10
Linux
Initially had some hitch but the documentation helped
https://github.com/meekMusa2/nillion-hacktoberfest
0x432d199df4Dee79C53A5BEa50cFE57FD51805c1B

Add Community example by meekmusa2

---

README.md

**How would you rate the usage of the npx create-nillion-app process
Give a rating / 10**
10/10
**What platform you run your CLI on
Mac / Windows / Linux**
Mac
**Did you get stuck during the CLI process?
Did you experience any issues while using the latest CLI and were you able to use the template?**
No Issues on setup. I was able to use the template.
**What is your Github repository link
Include the repository you worked on.**
https://github.com/ysongh/Wordle-BlindApp
**ETH Address (Optional)
Add your ETH address or ENS name**

Add Community example by ysongh

---

README.md
readme.md

10/10
Linux
https://github.com/denymosh/secret_addition
0x73BbBc86104Cc3450DA89e9c83f59b3f5aEb6b22

Add Community example by denymosh

---

README.md

10/10
Linux
No Issues on setup.Everthing worked smoothly.
https://github.com/asifbd11/secret_addition
0xeb9848E774d04aAF41E0025a51Cf57154649D2c0

Add Community example by asifbd11/

---

README.md

10/10
Linux
https://github.com/youngpriince/nillion-secret-addition
0xd39A82A57FdE8F11187b1A5C6731DB72D27C4413

Add Community example by youngpriince

---

README.md

How would you rate the usage of the npx create-nillion-app process ? (Give a rating / 10 )
8/10 
What platform you run your CLI on ? (Mac / Windows / Linux)
linux 
Yes! not working well for window. I'd to switch to linux 
No Issues
What is your Github repository link ? (Include the repository you worked on.)
https://github.com/Atunde-SS/secrete_addition 
0x70682E99c222248ff8d7a0078CB8Ee20600b9400

Add Community example by Atunde-SS

---

README.md

10/10
Linux
https://github.com/Rifat158/secret_additon
0x4a2C95Ccd772382577A5A9B00CbC829db83B644C

Add Community example by Rifat158

---

README.md

10/10
Mac
The CLI Installation process was seamless, i experienced no issue
https://github.com/hilary3211/Nillion-Blind-app.git
hilary.eth

Added Nillon example by hilary

---

README.md

10/10
Mac
I experienced no issues on setup
https://github.com/hilary3211/Morragame_Nillion_App.git
hillary.eth

Morragame app Hacktoberfest

---

README.md

9/10
Linux
I did have two errors. One was because I didn't have the python3-venv package (no helpful tips on the terminal, I got the clue from the tutorial video). The other one was on me for not reading carefully, cause everything was installed correctly but I had to close the terminal. Another thing to mention (not exactly related to the CLI), is that the .gitignore file is broken due to typos and spaces at the beginning of lines, so nothing is ignored when we push unless we fix it.
What is your Github …

[EXAMPLE] Add Community example by kenymccornick

---

README.md

10/10
Linux
No Issues on setup.
https://github.com/Mekong-labs/secret_addition
0x9C37B3A0e5c352f56cb8d7ed365cFfE1E686becE

Add Community example by Mekong Labs

---

README.md

10/10
Linux
hitchfree
https://github.com/Ore0luwa/nillion-blind
0x4473E36Da8fAaCA5f421D76edbCB6739a618f288

Add Community example by Ore

---

README.md

10/10
Linux
No Issues on setup.Enjoyed during the time.Everything worked properly.
https://github.com/niyana021/secret_addition
0xD9889FA374CC78B237d8Df463e8736d7DE4Af99F

Add Community example by niyana021

---

README.md

10/10
Linux
No Issues on setup.No problem faced.
https://github.com/divana0022/secret_addition
0x0F13D70A9C7D4661B57195AF9F443908aEc9daC2

Add Community example by divana0022

---

README.md

10/10
Linux
https://github.com/docpto/secret_addition
0x79609d1D8349C6daf7Af47944CCC1793e9F394A7

Add Community example by docpto

---

README.md

9/10
Linux
https://github.com/Paglrommo/secret_addition
0x9B9eD2585719ffF37cb6eF6D2e4Db032B30c1b78

Add Community example by Paglrommo

---

README.md

10/10
Linux
No Issues on setup.Everything worked like butter.
https://github.com/sufi121212/secret_addition
0x7353Ff779Cdcf827fA89e510B514be372cDa29AE

Add Community example by sufi121212

---

README.md

10/10
Mac
https://github.com/thu142857/tinybin-nillion-blind-app
https://github.com/thu142857/nillion-timeseries-blindapp
0xAdDb5Ce504adD8a07fFF03126571BBFb4F44d7c4

Add Community blind App (weather temperature guess + price trend prediction using timeseries)

---

README.md

How would you rate the usage of the npx create-nillion-app process ? (Give a rating / 10 )
9.5/10
What platform you run your CLI on ? I used windom
Yes
Yes I experienced many issues but with the help of the team ,I can able to solved it 
What is your Github repository link ? https://github.com/Oyedele23/appp_blind
ETH Address:
0xa28d63Dd08cE9a1ab5ac364b2bd720E862652307
Built my custom App - generate nillion_app

my contribution ti nillion_app

---

README.md

10/10
Linux
No Issues on setup.Firstly i faced some problem with nada installation.Then problem solved.And then everything worked perfectly.
https://github.com/Arifb121/secret_addition
0xeE3a8f7f63abbbb91F645E532a099560873cdE3F

Add Community example by Arifb121

---

README.md

10/10
Mac
https://github.com/daningyn/tinybid-nillion-blind-app
0x14A5095560250146cC3aadB5A7501D7b49d544C7

Add Community Vickrey Auction Secure Bid App by daningyn

---

README.md

10/10
Linux
No Issues on setup.No issues on setup.All the function worked smoothly.
https://github.com/kobirmiadev/secret_addition
0x74B773F86c31Ecc19711E547Fd8afEf6CE04B287

Add Community example by kobirmiadev

---

README.md

10/10
Linux
all good 
https://github.com/khalifalala1st/Blind-App
0x5522970eD9F2Ec3760D88A7fE423b1F429A8a37D

Added Community example by YoungKhalifa
